### ISSUE TITLE
SwiftBinaryProtocol will not build

### ISSUE THREAD

**Issue by svenn71** [mathias13/SBP#1]
1>------ Build started: Project: SwiftBinaryProtocol, Configuration: Debug Any CPU ------
1>CSC : error CS2001: Source file 'C:\work\prg\git\SwiftBinaryProtocol\SwiftBinaryProtocol\MessageStructs\BasePositionECEF.cs' could not be found.

**Comment by mathias13** [comment]
Try updated master branch.

**Comment by svenn71** [comment]
Pulled in master, and now it builds.
